version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - zoomit-web:/usr/src/app/
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_hereIroot
      - POSTGRES_PASSWORD=postgres_hereIroot
      - POSTGRES_DB=postgres_hereIroot
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/app/static

volumes:
  postgres_data:
  zoomit-web:
  static_volume:


 