version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - web:/app/
      - ./media/:/vol/web/media
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  db:
    image: "postgres:12.0-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres_heraIroot
      - POSTGRES_PASSWORD=postgres_heraIroot
      - POSTGRES_DB=postgres_heraIroot
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./static/:/app/static
      - ./media/:/app/media

volumes:
  postgres_data:
  web:
